service: code-build-test-api

provider:
  name: aws
  runtime: nodejs10.x

functions:
  sampleCalc:
    handler: handler.sampleCalc
    events:
      - http:
          path: hello
          method: get
          cors: true

plugins:
- serverless-offline